AllCops:
  TargetRubyVersion: 2.5

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'it']
